version: 0.2
env:
  variables:
    AWS_DEFAULT_REGION: ap-northeast-2
    ECR_DOCKER_TAG: 1
    ECR_DOCKER_IMAGE: dev-pipeline-demo
    ECR_URL: ${ACCOUNTID}.dkr.ecr.ap-northeast-2.amazonaws.com
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR....
      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${ECR_URL}
  build:
    on-failure: ABORT
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t ${ECR_URL}/${ECR_DOCKER_IMAGE}:${ECR_DOCKER_TAG} .
      - docker tag ${ECR_URL}/${ECR_DOCKER_IMAGE}:${ECR_DOCKER_TAG} ${ECR_URL}/${ECR_DOCKER_IMAGE}:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push ${ECR_URL}/${ECR_DOCKER_IMAGE}:${ECR_DOCKER_TAG}
      - docker push ${ECR_URL}/${ECR_DOCKER_IMAGE}:latest
artifacts:
  files:
    # - ecs_deploy_scripts/appspec.yml
    # - ecs_deploy_scripts/kill_process.sh
    # - ecs_deploy_scripts/run_process.sh
    # - ecs_deploy_scripts/imagedefinitions.json
    - codeDeploy_deploy_scripts/appspec.yml
    - codeDeploy_deploy_scripts/taskdef.json
  discard-paths: yes